# Generated by Django 5.2.6 on 2025-10-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer')], default='buyer', max_length=255),
        ),
    ]
